### ISSUE TITLE
Sign page improvements

### ISSUE THREAD

**Issue by Ranandcs1984** [samair/karattfoods#10]
The Full Name text box seem to trim (height) the characters typed.
Also the keyboard seem to be always at the top, we should be able to scroll it down dynamically. 
Right now only way to hide the keyboard is to press back button.
Thirdly, if we are trying to sign in with existing account; the information gets displayed at the bottom, lets keep a flash screen stating the user is already registered.

**Comment by samair** [comment]
Fixed with latest build. Please let me know
