### ISSUE TITLE
Forgot password while performing via "Sign-in with email"

### ISSUE THREAD

**Issue by Ranandcs1984** [samair/karattfoods#8]
During this screen, it prompts for mail id, but when we are typing the mail id, its in white font.
What we type is not visible and only the cursor keeps moving as we type.

Also the rest instructions over mail has not been received.

**Comment by samair** [comment]
Changed text color and hint info as well.

**Comment by samair** [comment]
Adding a new button , which will indicate loading
and  indicate email action

**Comment by samair** [comment]
Fixed.
